### ISSUE TITLE
Create branding for the tool

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#127]
The tool would benefit from having a logo, maybe some other branding things, making it more an identifiable entity.

**Comment by rvantonisse** [comment]
Will be done with #305

**Comment by hidde** [comment]
I'll consider this 'fixed in 2021', as we're adding W3C and WAI logo, WAI colors, typography and spacing ([preview](https://wcag-em-report-tool-2021-redesign.netlify.app/))

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), which is very branded! 🎨
