### ISSUE TITLE
Navigation has a fixed position

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#131]
The navigation bar should have a fixed position on the screen so users can reach it without having to scroll to the top. Care has to be taken that the bar doesn't take up too much screen space, and when it does some alternative solution should be provided.

**Comment by bakkenb** [comment]
I see that the top banner with Open, Save, Language menus is now fixed at the top of the page when scrolling. But was this comment about the "Start, 1-5, and View Report menu. Is that what they suggested be fixed at the top as well?

**Comment by WilcoFiers** [comment]
Thanks for the comment. I've considered that, but it seems to me that would take up too much screen space. Always having the save button available to you was a common question which didn't get picked up in v1.0. I see less value in having the option to always change steps in the middle of filling in a step. I'm open to considering it, but it can't take up too much screen space. This is particularly a problem in smaller viewports.

**Comment by bakkenb** [comment]
No, I completely agree with you Wilco. I was just wondering which one of the two navigation features they wanted fixed, the open, save, etc. or the steps. Sounds like it was the open, save, etc.

The latest version looks good to me.
