### ISSUE TITLE
Empty results aren't exported

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#135]
Right now every possible result is created for the tool. But for pages / criteria where no data is provided, the data should be removed from the JSON.

**Comment by rvantonisse** [comment]
Implemented on a sample level (left out of success criterion hasPart list) Not yet on top level success criteria. This is good behaviour. In this way a jsonld report tells the reader the audit is not done yet (having results with "untested")

Closing
