### ISSUE TITLE
Change font-size px to em

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#156]

**Comment by WilcoFiers** [comment]
Bootstrap 4 has announced it will use em/rem instead of px, which will solve our issue. We'll await this change until BS4 is released.
http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by davidberman** [comment]
Do we have a timeline on this? Because we need to eat our own cooking on this issue.

**Comment by rvantonisse** [comment]
See https://getbootstrap.com/docs/4.4/getting-started/download/ 

Will do soon if it is well implemented with a simple replace of code.

**Comment by rvantonisse** [comment]
Relate to #305

**Comment by hidde** [comment]
Added 'fixed in 2021 redesign' label as in the new version (feature/rebuild-svelte branch) we don't use Bootstrap or px for font sizes.

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
