### ISSUE TITLE
left-align all labels

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#172]
Left-align "Short name", "Address (URL)" (step 1,2,&3), "Web Technology", "Specification URI" (step 2), "Show/Hide results for individual web pages", "No pages selected under Sample to Evaluate" (step 4), "Report title", "Evaluation commissioner", "Evaluator", "Evaluation date" (step 5), and both summary tables in "view report"

**Comment by slhenry** [comment]
Stills needs to be done on Step 3.

**Comment by nitedog** [comment]
that is "short name" and "address (URL) or description" labels. also for "web technology" and "specification address (URL)", which will be moved to Step 2.

**Comment by WilcoFiers** [comment]
Left-aligned all the column headers and touched up the text flow a bit. Curious to see if people think this is better, this is how it looked originally and this seems a bit off to me.

**Comment by slhenry** [comment]
I'm looking at <http://w3c.github.io/wcag-em-report-tool/dist/#/audit/sample> and they're not left-aligned yet. Maybe I need to wait for a build or something?

**Comment by nitedog** [comment]
@slhenry yes, it is still the same build.

**Comment by WilcoFiers** [comment]
Yes, sorry about that. I close them as I'm working on them, but I have to build a preview manually, which takes a few minutes to do. You can preview my work of this weekend now.
