### ISSUE TITLE
Difficult installation instructions

### ISSUE THREAD

**Issue by iadawn** [w3c/wcag-em-report-tool#173]
I tried to create a local instance of the tool and ran into some difficulty with the installation instructions. There is a lot that is required and a fair bit of assumption in the Readme. Ideally a separate more comprehensive guide to getting everything up and running would be beneficial.

**Comment by WilcoFiers** [comment]
Updated the readme. I think this will help. If you come across any more problems feel free to open a new issue. Please try to be specific about the problems you're having.
