### ISSUE TITLE
Step 4: Sample page tooltip isn't closed when the link is clicked

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#174]
Because when the tooltip is clicked, a new window opens, the mouseleave event is never fired so it stays open, and because the tooltip toggles the visibility on an event rather then have exit always hide, and enter always show, the show/hide functionality is inverted.

**Comment by rvantonisse** [comment]
This:
<img width="421" alt="Screenshot 2020-01-20 at 16 02 14" src="https://user-images.githubusercontent.com/5967550/72736598-4c591700-3b9e-11ea-9e5a-c832ca601d14.png">

Is this disturbing? It does disappear when returning and clicking somewhere else, or moving focus.
Wont do.
Closing
