### ISSUE TITLE
Step 5: remove "No text provided"

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#188]
Either remove this text, or remove the "Findings" all together. Currently it looks like the evaluator should have entered something but missed to do so, while there is no requirement to actually provide an observation.

**Comment by nitedog** [comment]
We will leave it as-is for now. I left it open but moved it to V1.1, and marked it as "question" so that we look at it during usability testing.

**Comment by WilcoFiers** [comment]
@nitedog any new thought on this issue? We didn't get any feedback about this point during the user test. I think we're safe closing this.

**Comment by davidberman** [comment]
If keeping "no text provided", then perhaps add "Optional" to the label, so it is clear to the reader that the report is not incomplete... then change "no text provided" to "none".

**Comment by WilcoFiers** [comment]
I've removed the text and replaced it with a '–'.
