### ISSUE TITLE
Placeholder Text Issue for "Short Name" Fields

### ISSUE THREAD

**Issue by melodyma** [w3c/wcag-em-report-tool#191]
The placeholder text for "Short name" fields doesn't disappear on keydown. I think the colour of the placeholder text is not the right colour for placeholder text too.

**Comment by WilcoFiers** [comment]
Hi Melody! Thanks for reporting. These texts are not placeholder texts but default values. You can either leave them as is, or put in your own descriptor for the page (recommended). Which is also why they are the same color as other texts in input fields.

I think the behavior is correct, but obviously it shouldn't be confusing. Do you have any thoughts on how to improve on this?

**Comment by nitedog** [comment]
Hi Wilco! We discussed this in EOWG today. The problem is that these default values are confusing. They also hide the placeholder text, which explains what to enter. Can you remove the default values and have only the placeholder text appear?

**Comment by WilcoFiers** [comment]
Talked to Shadi about the solution earlier. We decided to take leave the handle field empty by default, so only it's placeholder is shown. The default names are now instead used only on the other pages if no page handle is provided. See a preview at:
http://w3c.github.io/wcag-em-report-tool/dist/#/audit/sample

Please confirm this has resolved the issue.

**Comment by melodyma** [comment]
Looks good!
