### ISSUE TITLE
Input text very light

### ISSUE THREAD

**Issue by yatil** [w3c/wcag-em-report-tool#192]
The contrast between placeholder text and usual input text is very minimal, they are almost indistinguishable.
Possible solution: Instead of using #555, use #333 (like other text).

**Comment by WilcoFiers** [comment]
Couldn't fully fix this. Even when entirely black the difference is minimal. As this is something that should be changed I opted for a different solution. The placeholder text is now italic, in addition to having a slightly better contrast.

**Comment by nitedog** [comment]
together with issue #191 this might be enough for now. more during usability testing.

**Comment by yatil** [comment]
Agree.
