### ISSUE TITLE
loading bug

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#194]
Steps:
- fill in website name (only)
- save JSON file
- load JSON file

Result:
- website name is empty

Firefox.

**Comment by WilcoFiers** [comment]
There was a problem importing the user, which could cause the entire import step to fail. Not just the report name. I think this was the cause of this issue, but please confirm that with the updated version this issue is resolved.

**Comment by nitedog** [comment]
solved - either by your update or by computer restart and mysterious javascript bugs
