### ISSUE TITLE
deleting web pages does not work

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#195]
Steps:
- add many web pages
- try to delete any

Result:
- X icon is not active

Firefox

**Comment by WilcoFiers** [comment]
Unable to reproduce this problem. Can you be more specific? How is the remove icon not active? Does it somehow look different? Are there any errors in the console maybe? How many pages did you add? Did you get it with both the structured and the random sample?

**Comment by nitedog** [comment]
ok, did some testing - interestingly enough it works via keyboard but not via mouse. again, here are the steps in more detail:
- go directly to Step 3 and to "Selected Web Pages"
- click "add web page" (reference to clicking important)
- try to delete that newly added web page *via mouse*
- the button "remove page" to the right is not clickable
- tab back to that button and it becomes activateable

tried on several browsers on Windows.

**Comment by WilcoFiers** [comment]
Still no success reproducing this. What version of Firefox are you running? I'll try a few different machines tomorrow at work. Maybe that helps.

**Comment by nitedog** [comment]
35.0.01 but i also tried several other browsers. the buttons are just not clickable. Maybe it's just my machine. I'll ask some colleagues to test tomorrow as well. Weird.

**Comment by nitedog** [comment]
restarted machine and it all magically works now! old school trick...
