### ISSUE TITLE
please move "Web Technologies Relied Upon" back to Step 2

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#196]
Too confusing in Step 3, after all. Please also put it _first_ in the order (before "essential functionality" and "variety of web pages")

**Comment by WilcoFiers** [comment]
Question: What do we do with the headings on step 2? Right now, with Tech Relied Upon as a heading, and Essential functionality, and Page types underneath it, it looks like these would be part of the Relied Upon heading. I Suggest we change the Web Technologies Relied Upon heading back to a regular label.

**Comment by nitedog** [comment]
Or make them all headings, since Techs Relied Upon already has labels?

**Comment by nitedog** [comment]
Better: how about adding a heading called "(Optional) Note Taking" above "essential functionality" and "variety of web pages"? you can then remove the word "(Optional)" from these two labels ("essential functionality" and "variety of web pages"). please also add an info box to this new heading, and I will provide the text for it (I added text to the intro paragraph but it is probably too long now - having an info box allows me to put these instructions there rather than in the intro paragraph).

**Comment by WilcoFiers** [comment]
The note taking heading looks nice. Do you want to add an info icon to this heading as well? The info boxes of Essential Func en Page Variety has repeating text. We could move that to a separate info box on the heading.
http://w3c.github.io/wcag-em-report-tool/dist/dummy.html#/audit/explore

**Comment by nitedog** [comment]
yes, please - add an info box to the heading "note taking" so that I can draw together the information currently repeated in the intro and the other two info boxes below that heading.

**Comment by WilcoFiers** [comment]
Done, once the info text is there this issue can be closed.
