### ISSUE TITLE
WARNING_BEFORE_UNLOAD not used?

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#200]
instead of the message in WARNING_BEFORE_UNLOAD, I get this message when closing the browser window: "This page is asking you to confirm that you want to leave - data you have entered may not be saved." (Firefox) - how can this latter message be customized?

**Comment by WilcoFiers** [comment]
Firefox does not support this feature of onbeforeunload, and appear not to have any intention to do so, since the bug is marked as 'wontfix'.
https://bugzilla.mozilla.org/show_bug.cgi?id=641509

There is nothing I can change about that unfortunately. Chrome and IE do show the custom message.
