### ISSUE TITLE
Analytics and privacy

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wcag-em-report-tool#206]
During the EOWG call on Feb. 20, I learned that WAI is planning to use analytics for this tool.  If this is correct, my understanding is that there will need to be some kind of privacy policy statement -- which is dependent on the kind of analytics being used (js and/or log file). Here, for example, is a Privacy Policy I helped develop to address this issue: http://vicc.org/nav/privacy.php.  It's linked in small text from the footer on almost every page of vicc.org.

**Comment by WilcoFiers** [comment]
There is currently no plan for any kind of analytics. If it ever comes up in the future we'll address this.
