### ISSUE TITLE
Indicate level of failures in Overview of audit results table 

### ISSUE THREAD

**Issue by iadawn** [w3c/wcag-em-report-tool#212]
Rather than just have a total view, include a break down by level as well - sometimes this needs to be reported and there is no easy way to find this out.

**Comment by WilcoFiers** [comment]
The table will look like this:

| Principle	 |Level A | Level AA | Level AAA|
|-------------|-----------|------------|--------------|
|1. Perceivable	| x/y | x/y | x/y |
|2. Operable	| x/y | x/y | x/y |
|3. Understandable	| x/y | x/y | x/y |
|4. Robust	| x/y | x/y | x/y |
|Total	| x/y | x/y | x/y |

**Comment by iadawn** [comment]
👍🏻

**Comment by davidberman** [comment]
Nice work. I recommend you <strong> the Total row: for most situations, that is the only total people want/need to know. 

Giving them a percentage on the totals would be pleasing too, especially in presenting 100% when they have achieved that.

**Comment by WilcoFiers** [comment]
Different breakdowns of the score table may also be interesting. I think that's something to include in a later version. One possibility is to break it down per 'section' of the website, as soon as tagging becomes possible. For now I think this is a good solution, not too controversial.

The one issue I had here was that if auditors leave criteria as untested, this won't show in the table. This could potentially be confusing, but I think it's up to the auditor to make the report clear. The report tool is better off just notifying the auditor that not all criteria are filled and have them decide how to handle it.
