### ISSUE TITLE
Remove hasPart from assertions

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#224]
hasPart works find for internal data structure but it's not a valid property of an EARL assertion. Instead page specific assertions should have the test property refer to the success criterion and it should differantiate based on that it's refering to a page instead of the scope.

**Comment by rvantonisse** [comment]
This is valid json-ld. EARL Schema 1.0 doesnt state you cannot use additional properties. For some classes it is even recommended to extend the class with other properties from dublin core terms for example the Assertor class.

I do however agree to remove subassertions as part of a hasPart property and instead group Assertions by succes criterion in the view (or something else in future) and simplify the current app model.

**Comment by nitedog** [comment]
@rvantonisse what is the latest on how you addressed this? cc. @hidde @mhansma96

**Comment by rvantonisse-accessibility** [comment]
This is adressed in the new tool wai-wcag-em-report-tool.
All assertions are on the same level inside auditresults.

**Comment by nitedog** [comment]
Thanks @rvantonisse, I added the corresponding label so that we close this issue after launch.

**Comment by hidde** [comment]
Yay thanks for addressing! The [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool) has now launched, closing this issue!
