### ISSUE TITLE
Use checkboxes for default web technologies

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#237]
Users can select technologies form the default set, and add their own with the existing functionality.

**Comment by WilcoFiers** [comment]
Relied upon technologies known in the report tool can now be added with simple select boxes instead of autocomplete text fields. For other technologies the text field is still available under the selection 'other'.

**Comment by davidberman** [comment]
Well done, having been frustrated with realworld use of the current tool, I find this a substantial improvement.
