### ISSUE TITLE
Menu: activating "Key Resources" causes reload

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#246]
> there is some bug in the menu - the "Key Resources" aren't accessible.
> When i click on the menu element, the page gets reloaded - same happens 
> when i tab to it and try to open it with the arrow-down-key.

**Comment by WilcoFiers** [comment]
Angular-UI changed their syntax. I've updated to the new syntax. Will prioritize removing Angular-UI from the dependencies as they are causing more problems then they are solving.
