### ISSUE TITLE
Order of individual results pages

### ISSUE THREAD

**Issue by iadawn** [w3c/wcag-em-report-tool#252]
In step 4, the order of individual results pages is random between different Success Criteria.

To reproduce:

* Add a number of pages (I have about 40)
* Move to step 4
* Select all pages in Sample to Evaluate column
* Expand 'Show web pages to enter individual results' for a number of Success Criteria
* Check that the order in each Success Criteria matches - they didn't in mind :(

**Comment by WilcoFiers** [comment]
Will look into it. I've been making a push towards 1.1. Will put this on the list. Thanks Kevin!

**Comment by WilcoFiers** [comment]
Finally figured this one out. Thanks Kevin, will be resolved in 1.1.

**Comment by iadawn** [comment]
👍🏻 Sorry to find the awkward ones!
