### ISSUE TITLE
Replace taskmanager Grunt for more modern module bundler X?

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#253]
i'm finding gulp significantly easier to reason about then Grunt. The tasks are getting quite large and messy, and with gulp this is easier to manage.

**Comment by rvantonisse** [comment]
Updating title to "Replace taskmanager Grunt for module bundler X?"

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which we use Rollup to bundle modules.
