### ISSUE TITLE
Allow indication when steps are completed

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#26]
There should be a way to indicate when some step is finished. Perhaps with a checkbox or with a separate button when going to the next step.

**Comment by WilcoFiers** [comment]
Proposed solution as of #263, needs feedback.

**Comment by rvantonisse** [comment]
Some input is required-like to get to a report that makes sense (e.g. Reporting findings without a sample or a website name).
A "completed" state can be calculated for each step based on "required"-ish fields. (e.g. Having no succuss criteria with result "not tested" makes the audit step complete-ish)

**Comment by rvantonisse** [comment]
Will elaborate
