### ISSUE TITLE
Move bootstrap row/col definitions from classes to stylesheets

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#266]
Currently, there is a lot of col/row definition in the HTML templates. This goes against the idea of separating concerns, and it makes the templates bloated and difficult to read. A better solution is to use the SASS mixins bootstrap provides:

https://github.com/twbs/bootstrap-sass/blob/881ce27c6b4101698ea849283933203e20861a33/assets/stylesheets/bootstrap/mixins/_grid.scss

**Comment by rvantonisse** [comment]
Bootstrap usage will be minimalized or replaced.

**Comment by hidde** [comment]
Added the 'fixed in 2021 redesign' label as in the new version (feature/rebuild-svelte branch) we no longer use Bootstrap.

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which we no longer use Bootstrap.
