### ISSUE TITLE
Create a menu option to change the language

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#269]
For each supported language, an option will be added to the menu, allowing the user to change the tool to that language. This will require a network connection, unlike most other features in the tool

**Comment by WilcoFiers** [comment]
English and Dutch are now included.

**Comment by davidberman** [comment]
Typically such controls show the current language selected, with "Language" as an invisible label. This makes the current selection visible. 

Language is selected rarely enough that it likely doesn't deserve an icon, and should perhaps not get as prominent a location.
