### ISSUE TITLE
Improve wording on the Start page

### ISSUE THREAD

**Issue by davidberman** [w3c/wcag-em-report-tool#272]
There are some key ideas that remain obscured on the Start page:
- "This tool does not automatically save the information that you enter." is a confusing warning. I think what we are trying to express is that the tool does indeed save your work as you go ... BUT you are going to want to save your work (and can do so at any point) to your local machine then continue later... and you must do so before closing your browser session.
- The "How this tool works" deserves a title such as "How to use this tool" and deserves integration with the Tips, and the "Note" should either move into that section, or be offset somehow as a Warning.
- Users deserve to know how accessible the resulting HTML report will be.  
- There are surface issues that deserve fixing on the Start page (e.g. "Mac shortcut keys S&#8984;S", "open in a new web browser windows", "show show", "For example, the website is only required..." ).

**Comment by WilcoFiers** [comment]
The "S⌘S" and the "show show" were my bad, thanks for catching those. As for the rest, can you suggest an alternative? The one thing I'm not sure about this the accessibility statement in the start page, if we need it at all, I don't think this information needs such a prominent position.

**Comment by rvantonisse** [comment]
Users are warned with a dialog when data is entered and trying to leave the page.
