### ISSUE TITLE
Terse accessibility statement to be added to the tool

### ISSUE THREAD

**Issue by davidberman** [w3c/wcag-em-report-tool#275]
priority: [medium]

location: last item on last existing bulleted list of introduction page

current wording/code: none

suggested revision: "Both the tool and the reports it generates meet or exceed WCAG 2.0 Level AA."

rationale: 
1. Users benefit from reassurance that everyone can use the tool. 
2. Users need to assess, before they invest time in the tool, that the report output it will generate will meet their needs.
3. Another example of our ability to show leadership by example in how people publish online.

(Wilco, I've also added this suggestion amongst the other suggestions that appear in the full draft I already shared with you offline.)

**Comment by rvantonisse** [comment]
Outdated? resolved?
