### ISSUE TITLE
translation.md - path

### ISSUE THREAD

**Issue by KerstinProbiesch** [w3c/wcag-em-report-tool#278]
"Once you have the wcag json file, copy it to app/scripts/wcag2spec/ and give it a name of wcag2-xx.json (where xx is the language code of the language to include)."

->

Once you have the wcag json file, copy it to app/wcag2spec/ and give it a name of wcag2-xx.json (where xx is the language code of the language to include).

**Comment by nitedog** [comment]
I believe translations, including this issue, are better addressed in [version 3](https://github.com/w3c/wai-wcag-em-report-tool).

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which translations work and are documented slightly differently.
