### ISSUE TITLE
Website name is not filled in in the report

### ISSUE THREAD

**Issue by julezrulez** [w3c/wcag-em-report-tool#281]
The content of Website name is blank in the report.
I used the Dutch translation of the tool.

**Comment by sirgazil** [comment]
I can confirm that, even when you specify a website name in Step 1 of the process, the **Website name** field appears empty in the **Scope of the evaluation** section of both, the **View report** page on the Evaluation Tool, and the HTML evaluation report generated for download. However, the JSON file does save the value of that field.

I'm using the English version.

**Comment by nitedog** [comment]
Thanks @julezrulez and @sirgazil! @WilcoFiers is the lead developer and we will try to get to fixing this bug as soon as possible.

**Comment by rvantonisse** [comment]
Fixed by @scottsb ! Thank you!
