### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by rotnicki** [w3c/wcag-em-report-tool#284]
I would like to create Polish translation.
Official Polish translation is available here: http://fdc.org.pl/wcag2/
Currently there is no json version of Polish translation.
Following your instructions I went to: https://github.com/WilcoFiers/wcag2json but there are no usage instructions how to use it.
How (step by step) did you create json versions of English translation?

**Comment by nitedog** [comment]
here are instructions for translation of this report tool:
 - https://github.com/w3c/wcag-em-report-tool/blob/master/docs/translation.md

many thanks in advance!

**Comment by rotnicki** [comment]
I think you misunderstood me.
In this file it states:

> The Wcag2Json project scrapes the HTML translations of WCAG and creates a JSON file for the Report Tool. These are available in different languages already. **The Wcag2Json project _has instructions_ explaining how to create JSON versions of other WCAG translations.**

But on the page https://github.com/WilcoFiers/wcag2json there are no instructions how to use this tool :(

I need to convert this Polish translation http://fdc.org.pl/wcag2/ into json format. But without those precise instructions how to use the wcag2json tool I am unable to do it.

**Comment by rvantonisse** [comment]
@rotnicki Hi hope I can help (if you haven't figured it out already):

If I understand the translation script of @WilcoFiers correctly you would have to:

1. Have [NodeJS](https://nodejs.org/en/) installed
2. Go to a cli app and `git clone https://github.com/WilcoFiers/wcag2json.git`
3. CD into the cloned repository and run  `npm install`
4. Create a folder named `wcag2-html` (script does not handle that)
5. Then you can use `npm run scrape <LANGCODE>`

There are a few languages present inside `translations.json` of which the Polish is one. In your case you should run `npm run scrape pl`

If you have created your own WCAG 2.1 Polish translations, or another language, similar to the layout / markup of W3C documentation you should be able to add that url to the `translations.json` file and run that script for a new WCAG-LANG.json version. -fingers crossed-

**Comment by rotnicki** [comment]
OK

---
Mikołaj Rotnicki


wt., 26 lut 2019 o 10:04 Roel Antonisse <notifications@github.com>
napisał(a):

**Comment by rvantonisse** [comment]
Closing, reopen if there are still some issues, will have to make an update to create newer WCAG 2.1 translations...
