### ISSUE TITLE
Support for HTML markup in observations

### ISSUE THREAD

**Issue by roelvangils** [w3c/wcag-em-report-tool#289]
To me, the WCAG-EM Report Tool would become a lot more useful if it allowed me to use markup (preferably Markdown) to write down my observations. Especially headings, lists, links, `code` and bolding etc. would be useful

![Interface screenshot](https://cl.ly/1y371Y0a3B2A/download/Screen%20Shot%202017-12-23%20at%2022.11.58.png
 "")

**Comment by nitedog** [comment]
The Authoring Tools Accessibility Report Tool (ART) allows for markdown; maybe there is reusable code there: https://github.com/w3c/wai-atag-report-tool/

**Comment by hidde** [comment]
Thanks, both! This has been addressed in https://github.com/w3c/wcag-em-report-tool/issues/379, reusing the ATAG Report Tool functionality!
