### ISSUE TITLE
The report "Show criterion text" button icon is completely unintuitive

### ISSUE THREAD

**Issue by accessiblewebuk** [w3c/wcag-em-report-tool#291]
It looks like a mortar-board hat. Have never seen it used anywhere and it doesn't give any obvious visual clues to its function. Here it is: 
![screen shot 2018-01-29 at 11 00 06](https://user-images.githubusercontent.com/18284458/35507140-a7f0b8a0-04e3-11e8-9811-5e66bba58ad9.png)

And here it is in context: 
![screen shot 2018-01-29 at 11 00 18](https://user-images.githubusercontent.com/18284458/35507146-b42e866a-04e3-11e8-83f6-a1c1f819adeb.png)

**Comment by rvantonisse** [comment]
Take into account with #305

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
