### ISSUE TITLE
broken link on the Report Tool start page

### ISSUE THREAD

**Issue by lclark070607** [w3c/wcag-em-report-tool#292]
There is a 'structured report' broken link.  It's located on the start page at this link:  https://www.w3.org/WAI/eval/report-tool/#/ The link is found under What This Tool Does accordion. I'm not what what the link is supposed to expose.  Is it to an example of an evaluated report or is it a link to the report tool itself?

**Comment by WilcoFiers** [comment]
Thanks Louise!

**Comment by rvantonisse** [comment]
Will be pointing to [view report](http://w3c.github.io/wcag-em-report-tool/dist/#!/view_report) with release 2.0.0
