### ISSUE TITLE
UI issue: The name of audit test cases do not trim themselves.

### ISSUE THREAD

**Issue by jeeyyy** [w3c/wcag-em-report-tool#297]
![image](https://user-images.githubusercontent.com/20978252/57075694-6c2e6f00-6cdf-11e9-8d1a-90147b492d81.png)

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
