### ISSUE TITLE
Adding link to page in the "audit sample" step

### ISSUE THREAD

**Issue by audreymaniez** [w3c/wcag-em-report-tool#304]
Thank you for the great tool :-)  

I just have a suggestion. In the "Audit Sample" step, in the right column when evaluating a particular SC, is it possible to change the text url for a real activable url ? 

![image](https://user-images.githubusercontent.com/409392/65520047-43ee1980-dee7-11e9-8bff-6d12ba4649ef.png)

Thank you!

**Comment by hidde** [comment]
This has been fixed in the 2021 redesign ([live preview](wcag-em-report-tool-2021-redesign.netlify.app/))

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
