### ISSUE TITLE
update visual design & a few misc

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-em-report-tool#305]
**_in-progress draft list:_**

update visual design based on current site specs:
* [x] font family, line-height, etc. - site css https://github.com/w3c/wai-website-theme/tree/master/_css
* [x] colors - https://wai-website-theme.netlify.com/components/colors/
* [x] logo and lines <s>(probably like [quickref](https://www.w3.org/WAI/WCAG21/quickref/), will confirm)</s>
**_UPDATE June 2020:_ [new header design](https://github.com/w3c/wai-website/issues/195#issuecomment-634759317) (implemented in ATAG Report Tool)**
* [ ] ...

also:
* [x] update footer (SLH will provide)
* [x] change language icon to /WAI/assets/images/icons.svg#icon-translations
* [ ] ? maybe move language list and change selection (SLH needs to think about it)
* [ ] make drop-down arrows in "menu" bigger
* [ ] ? ex-col buttons instead of arrow twisties

**Comment by hidde** [comment]
Added the 'fixed in 2021 redesign' label, as these issues should be addressed when we launched (let's make sure they are).

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
