### ISSUE TITLE
Would be nice to be able to import from axe or accessibility insights reports

### ISSUE THREAD

**Issue by mgifford** [w3c/wcag-em-report-tool#326]
Mostly wanting to reference an idea of @nschonni  & others here https://github.com/microsoft/accessibility-insights-web/issues/653

Shouldn't we be able to take these standard tools that reference WCAG and just import the information into a standardized report like the WCAG EM Report Tool?

**Comment by nitedog** [comment]
Thanks for relaying this @mgifford, would be delighted to continue this discussion. Adding @WilcoFiers too.

**Comment by mgifford** [comment]
Happy to see that https://github.com/dequelabs/axe-reporter-earl exists.  I hadn't heard of [Evaluation and Report Language (EARL) 1.0 Schema](https://www.w3.org/TR/EARL10-Schema/) before let alone the Axe Reporter EARL. 

Thanks @WilcoFiers for connecting the dots.

**Comment by mgifford** [comment]
Just noting that the axe-reporter-earl has been moved to axe-core-npm. The package will be available via NPM through @axe-core https://github.com/dequelabs/axe-core-npm/tree/develop/packages/reporter-earl

**Comment by hidde** [comment]
Added the 'fixed in 2021 redesign' label to this one, as the redesigned WCAG EM Report Tool (which lives in the 'feature/rebuild-svelte' branch) allows import of EARL reports.

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which EARL imports can be done.
