### ISSUE TITLE
No text for the key: AUDIT.LABEL_DESCR

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wcag-em-report-tool#328]
The app/views/directives/criterion/resultDescription.html file contains the key AUDIT.LABEL_DESCR:

```
<label class="sr-only" for="assert_desc_{{$id}}" 
  ng-bind="'AUDIT.LABEL_DESCR' | translate "></label>
```

There is no translation of this key in the language files (EN, NL)

Shouldn't the key "AUDIT.LABEL_ASSERT" be here?

**Comment by rvantonisse** [comment]
Thank you again for this finding, will fix.

**Comment by rvantonisse** [comment]
Fixed
