### ISSUE TITLE
string 'Close info' is not translated

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wcag-em-report-tool#331]
I found one more string that wasn't translated on line 18 in file app/views/evaluation/explore.html
``` html
<info-field ref="inf_reliedup_tech" button="Close info">
```
**It should be**:

``` 
<info-field ref="inf_reliedup_tech" button="{{'COMMON.BTN_CLOSE_INFO' | translate}}">
```

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
