### ISSUE TITLE
Inserting Screenshots

### ISSUE THREAD

**Issue by grifare** [w3c/wcag-em-report-tool#341]
In the "observations made during evaluation field", it is generally difficult to define where exactly the issue is, without a **screenshot**.
This can be achieved by encoding image to Base64 and embedding it using data URI that looks like this (much lengthier though):
`<img src="data:image/gif;base64,R0lGODdhAQABAPAAAP8AAAAAACwAAAAAAQABAAACAkQBADs" />`
This is one of the available [conversion tools](https://www.base64-image.de/)
Has this been considered before?

**Comment by rvantonisse** [comment]
See also the comments in issue #44

base64 crossed my mind as well, but I am a bit sceptic about the output in a json(-ld) file. (save functionality)

**Comment by hidde** [comment]
This functionality has been added in the 2021 rebuild (in the [rebuild/svelte](https://github.com/w3c/wcag-em-report-tool/tree/feature/rebuild-svelte) branch), which supports Markdown in observations. Images can be added using Markdown or HTML, either inline and base64 encoded, or linked as uploads.

**Comment by mgifford** [comment]
Looking forward to this addition.  US DHS has the screenshot functionality in their assessment tool https://github.com/Section508Coordinators/ACRT

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which you can add screenshots.

The tool strictly doesn't store any data, so you would need to store the image on your own server and can then reference it using Markdown syntax for images.

**Comment by mgifford** [comment]
That frankly is probably the best way to handle it given that this is all JSON.
