### ISSUE TITLE
Textareas collapse when returning to "4. Audit Sample"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag-em-report-tool#343]
Steps to reproduce:

1. Proceed to "4. Audit Sample" - https://www.w3.org/WAI/eval/report-tool/#!/evaluation/audit
2. In an "Observations made during evaluation" text field, enter two or more lines of text which cause the textarea to expand vertically. The entry can be two lines with a line break, or it can be a long line which wraps.
3. Proceed to a later step in the wizard, either "5. Report Findings" or "View Report".
4. Click "Previous step..." or "4. Audit Sample" to return to the view in step 1 above.

Actual Behavior:

Seen in Chrome version 80 / Windows 10.

At Step 4, the textarea is collapsed to a single line. This is confusing, in particular if the original entry had line breaks. It appears visually that everything after the first line has been deleted.

<img width="957" alt="Screen shot of Step 4. The first textarea contains two lines of text. The second textarea contains one line of text. They appear visually the same." src="https://user-images.githubusercontent.com/3124805/77396243-9efead00-6d60-11ea-9cae-9d3080ac92bc.png">

Compare with #265.

Expected Behavior:

Automatically expand each textarea to its height as in Step 2 (in steps to reproduce).

Alternative: default each textarea to a height of 1.5 lines, so there is a visual indication of which textareas contain more than one line. #

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
