### ISSUE TITLE
Step 4: "Select all web pages"-checkbox counterintuitive

### ISSUE THREAD

**Issue by miranausnerffg** [w3c/wcag-em-report-tool#349]
"Sample to Evaluate": 
If the "Select all web pages"-checkbox is checked, no web pages are selected. If it is unchecked again, all web pages are selected.
![Screenshot checkbox checked](https://user-images.githubusercontent.com/62592003/77429017-4ae3df00-6dd9-11ea-8df6-da79d298a6bb.png)

**Comment by rvantonisse** [comment]
That is the opposite of what it should do. Thank you for reporting.

**Comment by hidde** [comment]
We're addressing this in the 2021 redesign where it looks and works a bit differently ([preview](https://wcag-em-report-tool-2021-redesign.netlify.app/)).

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
