### ISSUE TITLE
Step 4: Fix label of textareas

### ISSUE THREAD

**Issue by miranausnerffg** [w3c/wcag-em-report-tool#350]
At the textareas "Observations made during evaluation" screenreaders announce the label as "AUDIT.LABEL_DESCR".

**Comment by rvantonisse** [comment]
Already fixed (But not yet published) see first mentioned in issue #328 and merged pull request: #330 
Will update latest preview version at github page of the tool: https://w3c.github.io/wcag-em-report-tool/dist/#!/ to be able to see updated changes.

Closing this issue when I have updated the preview version of the tool.

**Comment by miranausnerffg** [comment]
Thank you, sorry, I missed the existing issue!

**Comment by rvantonisse** [comment]
No worries, thank you for contributing!

Updated the [preview version](https://w3c.github.io/wcag-em-report-tool/dist/#!/) with the changes, closing.
