### ISSUE TITLE
JS is missing from the HTML download version

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag-em-report-tool#354]
When downloading a HTML version of the report, the buttons that expand the criterion explanation don't work. Looking at the console I can see the following error: 
`Uncaught ReferenceError: toggleCriterionText is not defined`

Looking at the source code I can see no references to JavaScript in that file.

**Comment by rvantonisse** [comment]
Duplicate (sorry, but thanks :) )
See: #290 and attempt to fix #302 (outdated :( )
