### ISSUE TITLE
[minor] tweak date information wording

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-em-report-tool#357]
In: https://www.w3.org/WAI/eval/report-tool/#!/evaluation/report

In Date information, add to:
> You can use any date format.

additional sentences:
> You can use any date format. Write out the month to make it clear internationally. (The date format 01-02-2022 is ambiguous — it is 2 January in some places and 1 February in some places.)

_(from new addition to [Style Guide, Dates](https://www.w3.org/WAI/EO/wiki/Style#Dates) based on https://github.com/w3c/wai-website/issues/213)_

**Comment by hidde** [comment]
I've just fixed this in the redesign!

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.
