### ISSUE TITLE
WCAG 2.1

### ISSUE THREAD

**Issue by roelvangils** [w3c/wcag-em-report-tool#362]
Does anyone know if there's a WCAG 2.1 version available of this JSON file? If not, I'm offering to build it.

**Comment by rvantonisse-accessibility** [comment]
Hey @roelvangils , 

> Does anyone know if there's a WCAG 2.1 version available of this JSON file? If not, I'm offering to build it.

Thank you for your question.

I am not sure what you mean by `...a WCAG 2.1 version available of this JSON file...`, but current reporter version contains this data file: https://github.com/w3c/wcag-em-report-tool/blob/master/app/wcag2spec/wcag2-en.json which has all 2.1 criteria written. This file comes from the wcag-quickref and has the techniques stripped from the data.

If you want to build or require a more official json file you should look at the WCAG repository. This contains a XSLT script to generate this data. The wcag buildscript: https://github.com/w3c/wcag/blob/master/build.xml

Let me know if this answers your question.

**Comment by roelvangils** [comment]
Thanks, @rvantonisse-accessibility. That was very helpful.

btw: I know see why my question was not very clear (I forgot to mention the file I was referencing to, but but you got it right) 😉
