### ISSUE TITLE
[Redesign] Display progress in “Your Report” box

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#368]
(stretch goal, depending on time available cc @nitedog)

The “Your Report” box exists to give context, some indication of how much evaluating was done helps users understand the state of the evaluation they are doing / have just imported.

This would likely count as broadly as possible, so _any_ comment tagged as related to `1.1.1 Non-Text Content` will count as an evaluation within “Perceivable”.  The point is to indicate whether any evaluation was done, and roughly how much.

<img width="285" alt="Your report for City of Rotterdam, with progress bars for each of Perceivable, Operable, Understanding and Robust" src="https://user-images.githubusercontent.com/178782/107379371-2544ee80-6aed-11eb-830b-5e0aed417522.png">

**Comment by nitedog** [comment]
Suggest only counting Success Criteria for which there are results on the **sample level**. For example, I have a sample of 10 pages and provide results on `SC 1.1.1` for all these pages but do _not_ provide an overall result for the sample, is counted as 0. Providing an overall result for the sample is counted as 1, regardless if I provide a result for any of the actual pages.

**Comment by hidde** [comment]
This is now working and added
