### ISSUE TITLE
[Redesign] Create component for “Show info” pattern in <label>

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#369]
WCAG EM Report Tool has “Show info” expandables that are positioned within form labels. These don't exist in the [WAI Design Components](https://wai-website-theme.netlify.app/components/). We do have a “show info” for headings and I suspect design could be very similar.

cc @nitedog @slhenry 

<img width="883" alt="scope of website field with extra info expanded" src="https://user-images.githubusercontent.com/178782/107379732-8240a480-6aed-11eb-8768-4706f9dfb7e9.png">

**Comment by nitedog** [comment]
Given your explanation, I think the title for this issue needs to change from "use component" to "create component"?

**Comment by hidde** [comment]
Thanks, you're right.

**Comment by hidde** [comment]
Removing from Milestone, because it does not impact the WCAG EM Report Tool itself.
