### ISSUE TITLE
[Redesign] Improve visual design for “Add more of type“ functionality

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#370]
Some parts of the WCAG EM Report Tool allow the user to add more of a certain time. for instance, “Add sample”, which adds a set of fields (URI, description) for a sample.

This issue is to improve the visual design for this component and potentially add it to the [WAI Design Components](https://wai-website-theme.netlify.app/components/).

cc @slhenry @nitedog 

<img width="885" alt="Screenshot 2021-02-09 at 15 46 19" src="https://user-images.githubusercontent.com/178782/107380213-f67b4800-6aed-11eb-9457-3919faa951bb.png">

**Comment by nitedog** [comment]
I like how "Address" and "Short name" appear on the same line (on most configurations) in the current design. I think it makes it less daunting and contextually easier to understand.

**Comment by hidde** [comment]
@slhenry said in EOWG 16 April consider proximity as well as putting them on one line

**Comment by hidde** [comment]
Kevin said in EOWG 16 April: this looks a bit skinny now

**Comment by hidde** [comment]
Have put Address and Short Name on the same line, made the delete function more subtle with an icon (and under the hood an accessible name), improved visual grouping so that each sampled page looks more like one. The background redundantly reinforces the grouping (low contrast, so only some users will benefit; could add border, but may be too much). 

Also: tested in Edge! 

<img width="863" alt="" src="https://user-images.githubusercontent.com/178782/115043318-ae551900-9ed4-11eb-858b-14720ebffa7d.png">

**Comment by slhenry** [comment]
much better spacing and proximity!

(Although personally I would like the field name a little closer to the field -- but no biggie :-)

**Comment by hidde** [comment]
thanks! I've removed half of the spacing between field name and field (8px to 4px to be precise).

<img width="620" alt="Screenshot 2021-04-20 at 14 37 15" src="https://user-images.githubusercontent.com/178782/115397019-e8c8f980-a1e5-11eb-99e7-a298a5c817fc.png">
