### ISSUE TITLE
[Redesign] Let users choose sample per issue, while they add an issue, and remove “sample sidebar”

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#371]
## Current

In the current prototype, there is a sidebar on the left that lists all samples and lets you check/uncheck and go to individual sample pages. This functionality also exist in the current live WCAG EM Report Tool, and seems to [confuse some](https://github.com/w3c/wcag-em-report-tool/issues/349).

<img width="878" alt="screenshot of what's described above" src="https://user-images.githubusercontent.com/178782/107380970-a650b580-6aee-11eb-8598-43997fff07bb.png">

### What is the proposal

My proposal is that we remove the “Sample to evaluate” sidebar, and add the functionality of “select which samples to report about” to the SC, with these features:

* Add a dropdown. Currently we have “Outcome“, I propose we have “Outcome” and “Sample”
* In the “Sample” dropdown, allow to choose between “All” (the identified issue applies to all pages or none in particular) or one of the samples defined in previous steps. This moves the list of samples that was displayed on the left to a dropdown that appears for each individual issue
* Add a button underneath that lets user add a new issue for the SC

### How could it make things better

* Save space. Evaluating is now one column rather than two, it is no longer crammed in a small space.
* No more separation between issues that apply to all of the sample vs specific sample pages. Instead of having two separate sets of issues, it is now a parameter per issue. Each observation can be set to apply to 'all' (special case), or any of the sample names ('sample x', 'sample y', 'sample z', whatever the user has called them).
* More logical timing: when an auditor finds an issue, they do this on a page, so it makes sense to select what that page is when they are reporting the issue.
* Removes the need for a form per sample page. User can now flexibly add issues for this SC, whether they are all in one sample, or in various different samples, or in no particular sample at all, with just one simple dropdown.

<img width="731" alt="screenshot of what is described above" src="https://user-images.githubusercontent.com/178782/107381402-15c6a500-6aef-11eb-878d-b5e19a2b6aad.png">

### Example with more content

<img width="704" alt="screenshot like above, but with three issues added, all in different samples" src="https://user-images.githubusercontent.com/178782/107382657-6c80ae80-6af0-11eb-9b60-17caf62f62e5.png">

**Comment by nitedog** [comment]
I personally like this direction but would want to confirm with a few more people who do evaluations more regularly (eg. folks in ACT). Happy to help with that.

Meanwhile, thoughts on some specifics:

1. Terminology: "Sample" should probably be "Web Page", "All" should probably be "Overall" or "Entire Sample" or such, and "Outcome" and "Issue" should probably be "Result"
2. It is not really clear to which page the results and observations relate because it appears at the end and in a pull-down menu. I suggest:
  - Adding a heading saying something like "Results for Page X"
  - Combing "add another result" and "select page" functions (not sure which design pattern, though -- maybe a dialog?)

**Comment by hidde** [comment]
> I personally like this direction but would want to confirm with a few more people who do evaluations more regularly (eg. folks in ACT). Happy to help with that. 

Good idea! I have reached out to some people that I know use the current tool, would be happy to introduce it at a future ACT meeting.

> Terminology: "Sample" should probably be "Web Page", "All" should probably be "Overall" or "Entire Sample" or such, and "Outcome" and "Issue" should probably be "Result"

The way I've come to think about it is that an auditor files bugs. They say “X is the case and it is a violation of WCAG”. In this interface, they which SC it is related to and on what page it happens, so that the team can get to work. 

Of course, there is also the perspective of: the auditor writes down in which ways WCAG is met and/or violated, so that regulatory bodies can understand what the level of conformance is on a given website and compare it to other websites.

I feel a word like “issue” is suitable for that 'tell a team what's wrong' perspective, whereas the word “result” is more suitable for that ‘understand conformance as a regulator’ perspective.

And there are problably more perpsectives, too.

> It is not really clear to which page the results and observations relate because it appears at the end and in a pull-down menu. I suggest:
>  *  Adding a heading saying something like "Results for Page X"
>  *  Combing "add another result" and "select page" functions (not sure which design pattern, though -- maybe a dialog?)

In the proposal, the dropdown under “Sample” has the "Select page" functionality.

In some auditing software I've seen people distinguish between pages and components, that might also be something.

For instance, there may be an accessibility problem in the header of the page, which exists on all pages, so it would file under “header” rather than “Page X”. Or in the datepicker, used in 5 different forms, so it could file under “datepicker” rather than “Page Y”.

“Pull down menu” may feel hidden away, but it would be filled with the names that the auditor themselves have come up in an earlier step, I am hoping that helps a lot in recognising what it is for.

**Comment by hidde** [comment]
Discussed with Shadi:

* Name of dropdown “Sample” should be “Web Page”
* Instead of “All”, use “Entire Sample”
* Change “Outcome” to “Result“
* Use “Add another result”
* The first entry is always “entire sample”, it is fixed and has no “Web Page” selector

**Comment by rianrietveld** [comment]
I like @hidde's suggestion of selecting the webpages that apply per SC, because that is exactly my normal workflow. 
Per SC there are issues, some in all pages, some in one or a few  pages. 

Indicating per SC where the issues occur in the report with the observation, will make the report much more readable and uniform. And less time consuming to fill out.

I'll leave the naming to the native English speakers. 😄

**Comment by hidde** [comment]
Discussed with Shadi: 

- button would add observations for a specific page in the sample

**Comment by hidde** [comment]
Suggestion: let's take this issue out of scope for the next iteration, as it is too much work to build and test, and the [proposed position and simplicification of the sample picker](https://github.com/w3c/wcag-em-report-tool/issues/374#issuecomment-818601895 ) probably addresses the problems sufficiently for now.

**Comment by hidde** [comment]
Closing for now because for the reasons above.
