### ISSUE TITLE
[Redesign] Simplify buttons in “Your Report” box

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#373]
In the current situation, the “Your Report” box has four buttons. I think it would work best with fewer buttons. cc @nitedog 

### Only have “New Report” on the Overview page

Rationale: 

* Consistency with ATAG Report Tool

### Improve “Open Report” and “Import Data” situation

Rationale: 

* These buttons do similar things, having them both to choose from may be complex. We may be able to improve this by embedding them in more _context_.

#### Suggestion A: Combine the two

What if there was one button, “Import”, and it would ask a follow up question of “a full report or some evaluation data” and/or “want to replace existing data, or add on top of existing data”?

#### Suggestion B: Display “Import Data” inline in audit page

“Import Data” may be a thing we do just in the audit page, as, as far as I understand, it imports evaluation results. 

We could therefore move it to the audit page rather than have it available on every page?

<img width="1189" alt="screenshot of audit page with import button as part of content and removed from your report page" src="https://user-images.githubusercontent.com/178782/107502171-a2796d80-6b98-11eb-926a-1fe2299f4fbe.png">

**Comment by nitedog** [comment]
I **really** like the idea of "Import data" function on the "Audit Sample" page (Suggestion B)!

**Comment by hidde** [comment]
Cool! 

Another thing we do in ART that may work here, too: the 'New Report' button only exists on the homepage. This yields less buttons on most pages. 

How would you feel about that?

**Comment by hidde** [comment]
Discussed with Shadi this morning: 

- we'll move  the “Open report” and “New report” buttons to their own area in the content of the Overview page (like Import data is included in the content of the Audit page https://github.com/w3c/wcag-em-report-tool/issues/388), as this is different functionality from what “Your report” does
- “Your report” could either not show on the Overview page, or show with no content

**Comment by hidde** [comment]
This was fixed in #400
