### ISSUE TITLE
[Redesign] Add Markdown support for fields

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#379]
Like we do in the [ATAG Report Tool](https://www.w3.org/WAI/atag/report-tool/report), on:

* observations
* management summary

**Comment by nitedog** [comment]
Technically this is a feature request rather than a UI redesign issue but I think it is seamless enough that we can slip it in...

**Comment by rianrietveld** [comment]
+ 💯  for this suggestion.
That will make the report so much more flexible and readable to set up.

**Comment by hidde** [comment]
This was fixed in #391
