### ISSUE TITLE
[Redesign] Add summary of results, including “Not checked”

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#381]
* [x] Add summary of results
* [x] Add list of unchecked under 'Not Checked' heading
* [ ] Add SC handles to “Not Checked” results

Like in the ATAG Report Tool [results](https://www.w3.org/WAI/atag/report-tool/report#results)

<img width="1240" alt="heading Summary; Reported on 9 of 52 Level A, AA Success Criteria; 4 Passed; 3 Failed; 1 Cannot tell; 1 Not applicable 43 Not checked" src="https://user-images.githubusercontent.com/178782/107647579-99ad9800-6c7b-11eb-97a2-0ca7513dd8e1.png">

Under the “Not Checked” heading, the user can find links to individual SCs for which nothing was reported.

<img width="1230" alt="" src="https://user-images.githubusercontent.com/178782/107647909-f7da7b00-6c7b-11eb-8c6d-f95a09470bbd.png">

**Comment by nitedog** [comment]
This might need a brief explanation of how the counting works. Maybe with a "show info" button?

**Comment by hidde** [comment]
Agreed. We may also be able to work it into the “Reported on…” sentence? 

Confusion could be in:

* evaluation target (are we counting WCAG 2.0, 2.1, maybe even 'only new 2.1' criteria')?
* what “Reported on” means. I remember we did discuss this in EOWG, so maybe it is clear enough… 
* if it is in specific samples or overall, maybe we need to add something like “across entire sample”

**Comment by hidde** [comment]
This is now available in the [preview](https://wcag-em-report-tool-2021-redesign.netlify.app/). 

(To see, navigate to 'Audit sample' (needed because https://github.com/w3c/wcag-em-report-tool/issues/414), optionally set some SCs to 'Passed' or 'Failed', then navigate to 'View report')

To address your comment, @nitedog, I have made sure to include which target (2.0, 2.1 etc), and added 'not checked' list just like in the ATAG Report Tool.

If you have suggestions for wording, like 'across all web pages in scope', we can add it.

**Comment by nitedog** [comment]
Looks good to me! Maybe include SC handles in addition to SC numbers (like in ART)?

**Comment by hidde** [comment]
Have just added the handles in addition to numbers through https://github.com/w3c/wcag-em-report-tool/commit/5ea170e3c0adedce4ed9400a68e2d084b635d02e
