### ISSUE TITLE
[Redesign] Data is not saved locally and disappears on reload

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#383]
When you accidentally refresh the page or close the tab, all of the data disappears.

In the ATAG Report Tool, this problem is solved by backing up all data in `localStorage` when the user changes any content.

**Comment by nitedog** [comment]
I think this is a feature request and out of scope for this UI redesign?

**Comment by nitedog** [comment]
On the short term, and alert will be added to avoid losing data. On the long run, issue #7 already exists.
