### ISSUE TITLE
[Redesign] Use on:blur in Select component for better accessibility?

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#385]
<img width="879" alt="(!) Plugin svelte: A11y: on:blur must be used instead of on:change, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users. Code example pointing to line 12 to 15 in Select.svelte" src="https://user-images.githubusercontent.com/178782/107754944-7b4ea780-6d22-11eb-825e-4522335257ec.png">

@rvantonisse Do we need to use `on:blur` here? What does this attribute do anyway with no event handler attached (I would expect `on:change={someFunction}`?)

**Comment by rvantonisse-accessibility** [comment]
@hidde Hey I looked this up as well and answers concerning accessibility issues go back to IE 6 .... really old. search for it you'll see a lot of discussion. Issue was that it would apperently trigger a lot, also when there was no change at all... But that is not the case anymore.

In this case this is used to store the outcome value `on:change="{handleOutcomeChange}"` or something. I am ok with using on:blur if the data still gets in there.

**Comment by hidde** [comment]
Cool, will double check and update.

**Comment by hidde** [comment]
fixed in https://github.com/w3c/wcag-em-report-tool/commit/0a0d5b08619f92d8fcbc87bf9665e4b261ceacdf

**Comment by hidde** [comment]
Reverted as @rvantonisse asked to investigate a potential bug this caused.

**Comment by hidde** [comment]
Closing this issue, it broke more than it fixed. 🙄
