### ISSUE TITLE
Update Web Technologies Relied Upon to modern web techniques

### ISSUE THREAD

**Issue by rianrietveld** [w3c/wcag-em-report-tool#390]
The items listed in Web Technologies Relied Upon contain old / outdated web techniques like XHTML 1.0, HTML 4.01, Flash and Silverlight.
Update the list with more modern techniques like for example JavaScript.

If older techniques are used, the next field Web Technology can serve as backup.

**Comment by nitedog** [comment]
We could reduce this list to the following:

- HTML
- CSS
- WAI-ARIA
- JavaScript
- SVG

**Comment by hidde** [comment]
Thanks @rianrietveld and @nitedog for this suggestion, I have updated the list as per in https://github.com/w3c/wcag-em-report-tool/issues/390#issuecomment-779838881 in PR #392.
