### ISSUE TITLE
[Redesign] Add user feedback when open or import

### ISSUE THREAD

**Issue by rvantonisse-accessibility** [w3c/wcag-em-report-tool#395]
To give users a sense of what is happening when they try to open an existing evaluation or try to import data to their audit, user feedack is required.

# Situations

## Open report

When a user clicks / touches the “Open report“ button, the tool will let the user choose a json file which represents an evaluation done with this (previous) tool. The tool will try to open and parse the json as json-ld which should be output of this (previous) tool and then load it as the current evaluation.

### The following errors may occur

- JSON-LD SYNTAXERROR; The json file contains non valid json-ld syntax. This may occur either through altered contents or using an evaluation from the very first version of this tool (less likely).
- CORRUPTED FILE ERROR; The contents of the file may have been altered manually, which can result in this error. Specificly occurs on missing / altered keys.

## Import data (step 4 Audit)

When a user clicks / touches the “import“ button in step 4 Audit, the tool will let the user choose a json file which should represent any json-ld with properly defined EARL Assertions. **The source of the json file does not matter** as long as it represents json-ld containing EARL Assertions. The tool will try to open and parse the json-ld which should result in a list of potential results (Assertions) that can be asserted to the current evaluation. To be able to use this function a user must have at least one sample defined in step 3.

The tool will check if any of the Assertions found meet the minimal required values set: test, subject and result. Then collects and group all Assertions that match a test and subject. And finally will assert all grouped results to the appropriate observation field in the audit page.

### Errors that may occur

- JSONLD SYNTAX ERROR; The json file contains non valid json-ld syntax.
- NO ASSERTIONS ERROR; The json file does not contain EARL Assertions.
- NO COMPATIBLE ASSERTIONS; The json file does contain EARL Assertions, but none match the required criteria.

### Confirmation messages that may occur

A user may decide to continue with the import or not.

- IMPORT READY; All or some of the found Assertions are ready to be imported.

### Success messages

- IMPORT DONE; Import was successfully done.

**Comment by rvantonisse-accessibility** [comment]
@nitedog could you provide the en message format for mentioned situation errors and confirmations? If anything is missing add too please.

Thank you!

**Comment by nitedog** [comment]
> JSON-LD SYNTAXERROR; The json file contains non valid json-ld syntax. This may occur either through altered contents or using an evaluation from the very first version of this tool (less likely).

I suggest: `Open failed: file format is not recognized.`

> CORRUPTED FILE ERROR; The contents of the file may have been altered manually, which can result in this error. Specificly occurs on missing / altered keys.

What happens here, does the script stop or does continue with partial data?

If it stops then I suggest: `Open failed: file data seems incomplete or altered.`

If it continues then I suggest: `Warning: file data seems incomplete or altered. Do you want to continue?` with the options to continue or stop the script.

Please also add a success message:

I suggest: `Open successful: your report was updated with data from the selected file.`

> JSONLD SYNTAX ERROR; The json file contains non valid json-ld syntax.

I suggest: `Import failed: file format is not recognized.`

> NO ASSERTIONS ERROR; The json file does not contain EARL Assertions.

I suggest: `Import failed: the file contained no recognizable assertions.`

> NO COMPATIBLE ASSERTIONS; The json file does contain EARL Assertions, but none match the required criteria.

I suggest: `Import failed: none of the assertions in this file matched the selected sample.`

> IMPORT READY; All or some of the found Assertions are ready to be imported.

I suggest: `Confirm: X matching assertions found. Do you want to continue?` -- I think you were displaying the number of found assertions in your alerts?

> IMPORT DONE; Import was successfully done.

I suggest: `Import successful: assertions were added to the observations on this page.`

**Comment by hidde** [comment]
@nitedog could you check if you're happy with the feedback that is currently implemented?

If you are, we can close this issue.

**Comment by nitedog** [comment]
Issue 1: got this incorrect error message when opening a wrong JSON document:

> Import aborted:
> 	UI.IMPORT.ERROR.NO_COMPATIBLE_ASSERTIONS

Issue 2: did not get *any* message when importing incorrect JSON files

Issue 3: did not get *any* message when importing non-JSON files

...

**Comment by hidde** [comment]
Thanks! This means this issue is still open. It shouldn't block opening the survey if we add it as a known issue, I think, but needs fixing before release.

**Comment by mhansma96** [comment]
I've added a pull request (https://github.com/w3c/wcag-em-report-tool/pull/473) with some changes that should fix these problems. Among these changes:
1. Not properly translated error messages should be working now. I've added missing ones to the translations file.
2. Non- or incorrect JSON files should now give an error message as well. I've added this new translation so if someone wants to review the text, please do so.
3. I noticed that all the error messages where not present in the Dutch version, so I added them as well.
4. There was a small bug, I encountered it while testing the errors, with importing the same file twice in a row. Because the import button is looking for an _onChange_ event, nothing happens. So I added a fix for this.

I would be great if someone could help evaluate these changes when the pull request is merged because I don't have many JSON-testfiles yet to check every error scenario properly. Also since I added some missing translations (mostly in Dutch) I would be great if someone could review them so they align with the use of certain terms and standards throughout the whole tool. Changing the translation text is not blocking because now that they are there at least, it's only a matter of changing the text

**Comment by hidde** [comment]
@nitedog These changes are now in the [main preview](wcag-em-report-tool-2021-redesign.netlify.app/); could you check if the feedback is as you would expect it?

**Comment by nitedog** [comment]
I couldn't test all situations but it is looking good now! Will you @hidde and @mhansma96 provide test files in the repo at some point?

**Comment by hidde** [comment]
Cool! Will close this issue, then. 

I have started a test file page in [the wiki](https://github.com/w3c/wcag-em-report-tool/wiki/Example-report), opened https://github.com/w3c/wcag-em-report-tool/issues/476 to track the work of creating more test reports with the current tool.
