### ISSUE TITLE
[Redesign] Set other font family for form text input

### ISSUE THREAD

**Issue by rvantonisse-accessibility** [w3c/wcag-em-report-tool#401]
Hey @hidde ,

I noticed when entering data in text inputs with the set font, backtics (`) are not displayed well. They seem not to occupy any space. There should probably be another font family set for form elements.

Backtics are used to add code fragments in markdown, which is supported for Audit results.

macOS, Chrome browser.
Current font set "Noto Sans".

**Comment by hidde** [comment]
Yes, this seems to be a problem in the font. In the ATAG Report Tool, we use `"Noto Sans Mono", monospace` as the font family for textareas for this reasons. Not the prettiest, but it works. Let's do that in WCAGEMRT too (cc @nitedog )

**Comment by hidde** [comment]
Happy to pick this one up, just self assigned.
