### ISSUE TITLE
[Redesign] Visually indicate Markdown support with textareas that support it

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#425]
Proposal for textareas that support markdown: 

* add “Markdown supported“ to `label`, visually hidden. For example, label “Observations for 1.1.1” becomes “Observations for 1.1.1, markdown supported”
* add Markdown icon underneath text area, hidden from assistive technologies

This would indicate Markdown support to non-visual users via the label and to visual users via the icon. The approach assumes that visual users understand the icon to mean “Markdown supported”.

<img width="447" alt="screenshot of observations field with the official Markdown icon underneath the textarea, gray, right aligned" src="https://user-images.githubusercontent.com/178782/117144239-fc618c00-adb1-11eb-8284-1e40ddc17bf3.png">

Other possibilities: 

* link to Markdown syntax / explanation of Markdown on overview page
  * option 1: add link with link text “Markdown syntax” / “Info on Markdown support”
  * option 2: make the icon the link, with “Markdown syntax” / “Info on Markdown support” as alt text
  * option 3: don't add link because field can appear ten times on a page and repeating is annoying
* have text “Markdown supported” visible for all, so that icon is redundant
* have text “Markdown supported” visible for all, remove icon

**Comment by hidde** [comment]
@nitedog today I have reviewed the discussions on this functionality for the ATAG Report Tool  https://github.com/w3c/wai-atag-report-tool/issues/89, and found that most variations are discussed there, we landed on just mentioning it on the homepage, might we decide the same for the WCAG EM Report Tool? The tab stops argument there is stronger in this tool, as in the WCAG EM Report Tool, the component repeats more times on one page, resulting in more tab stops.

I'm removing this task from this week's Milestone as we'll need consensus on what we want to implement here.

**Comment by nitedog** [comment]
Thank you for referring back to the prior discussion!

From a quick skim, I didn't find a proposal where the "M"-icon appears *after* the input box as in this latest proposal. Did I miss it in the earlier thread or is this a new proposal?

**Comment by hidde** [comment]
It is a new proposal, to address the tab stop issue: when it is part of the label's accessible name, it basically reuses the input's tab stop. 

It also tries to learn from how GitHub does it, as seen near the comment box on this page (sorry, a little meta :-)) GitHub also adds a tooltip on hover, I would guess to address that visual users may not know what the icon means (I know I didn't until recently).

**Comment by hidde** [comment]
Solution for now: add information on Markdown to the homepage.

**Comment by hidde** [comment]
Closing as we'll no longer do this, moving content suggestions and Markdown explanation to https://github.com/w3c/wcag-em-report-tool/issues/447
