### ISSUE TITLE
[Redesign] Hovers unclear or badly visible

### ISSUE THREAD

**Issue by mhansma96** [w3c/wcag-em-report-tool#438]
The menu items and navigation items (top of the screen and bottom of the current tab) to go between the steps don't have a hover or an almost invisible one

**Comment by hidde** [comment]
Based on this feedback, I've just added a hover style to the CSS that this tool uses (“Guideline 2” would be hovered): 

<img width="959" alt="menu bar with Guideline 2 item that is slightly darker and has a yellow underline" src="https://user-images.githubusercontent.com/178782/121209620-45a66f00-c87b-11eb-9340-2d353f5cae69.png">

It folllows the sample principles as the main WAI navigation: slightly darker background and yellow underline. 

As we're deeplinking the WAI CSS, these updated styles will show up in this tool next time the WAI website is deployed. 

 cc @nitedog @shawna-slh

**Comment by shawna-slh** [comment]
Hi Hidde.

In the main nav of the WAI website, the text is white text on blue background. Hover (and focus) gets white on darker blue background -- so **increased contrast**.

In the minimal nav bar, it is dark text on light blue background. If hover gets darker background, then it gets less contrast. How about being consistent with the **more contrast**, which would be the background would get lighter on hover/focus?

(Also need to add it to focus, looks like.)

**Comment by hidde** [comment]
Oh that's a great suggestion! Will update it to become lighter rather than darker on hover.

For focus we're using black outlines, I guess they are probably most effective as they are (because easier to follow the rectangle along as it is the same on all focused elements)?

**Comment by shawna-slh** [comment]
+1 for outline consistently on focus
*and* I prefer consistency between hover and focus.
For main nav, how about *both* outlines and lighter background with yellow underline for focus (like the main WAI site nav does)?

**Comment by hidde** [comment]
Aah, sorry, I did not realise we had both on the WAI site, have just updated the style to affect both hover and focus.

Have also made the background lighter rather than darker.

<img width="459" alt="" src="https://user-images.githubusercontent.com/178782/121243844-7b108400-c89e-11eb-857f-84edcea1e222.png">

**Comment by hidde** [comment]
This is now updated, thanks for the input @shawna-slh!
