### ISSUE TITLE
[Redesign] Users will only find out about the export-function on the home and report screen

### ISSUE THREAD

**Issue by mhansma96** [w3c/wcag-em-report-tool#439]
During the audit step, you can be unaware that there is a option to export and save your progress for next time. We could look into an extra solution to make this clear in order to prevent user errors or potential frustration with loss of progress.

If we use localstorage to save progress, this issue can change to simply making a user aware of the saving-process in a more visible way.

**Comment by nitedog** [comment]
We previously decided against using localStorage because:

1. Evaluators are sometimes working on multiple reports at the same time, in which case localStorage seems to get in the way
2. It is quite a lot of coding work that we could not fit in the scope of this upcoming release

**Comment by mhansma96** [comment]
Those are valid arguments. But that underlines the essence of making the user aware of this. So I think this issue should be picked up at some point. 

As stated it is in a block of text on the homepage that can easily be skipped, and on the report tab, that you might not have visited yet as a user. So besides a confirm-warning when closing the page, I would say looking into adding a block with some text and possibly the export-button on the audit page makes sense. Also because the import button with text is already there, we could maybe do something similar to cover more user errors?

**Comment by nitedog** [comment]
No disagreement with the issue, I was just pointing out the reasons for the previous decision against **localStorage**. In the [current version](https://www.w3.org/WAI/eval/report-tool/), there is a permanent toolbar at the top where the "Save" button was always available. There was a decision to remove this toolbar, which I guess led to this issue. Maybe we need to add some sort of a "Save" button to the sidebar?

Side note: @hidde and I had talked about adding a "Reset" button that appears in the sidebar as soon as the user enters any data -- maybe the combination of "Save" and "Reset" buttons in the sidebar makes sense.

**Comment by hidde** [comment]
Linking issue https://github.com/w3c/wcag-em-report-tool/issues/7 re localStorage. From my perspective it is not a lot of programming work as we already have it in the ATAG Report Tool. The multiple reports issue could be solved by users with container tabs or multiple browsers, or by us by providing an on-by-default checkbox at the start to turn localStorage functionality off.

**Comment by hidde** [comment]
I think there's nothing we can do currently about this issue; localStorage would help a lot, but until we solve #7, we'll keep the  download buttons on the last page, which aligns with the ATAG Report Tool.
