### ISSUE TITLE
Clearly state the software license

### ISSUE THREAD

**Issue by mgifford** [w3c/wcag-em-report-tool#440]
I assume this is released under a MIT license, but would be good to have the licensing clear in a LICENSE.txt file and in the README.md file so that it is easy to find.

**Comment by hidde** [comment]
Thanks Mike, will find out what we can do and get back to you!

**Comment by shawna-slh** [comment]
Hi Mike. It's actually under W3C license. https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
That's linked to from the footer (though from "Copyright" and "Usage policies apply.".
Hidde will also add LICENSE.txt

**Comment by hidde** [comment]
Have just added a link to the license: https://github.com/w3c/wcag-em-report-tool/blob/feature/rebuild-svelte/LICENSE
