### ISSUE TITLE
[Redesign] Homepage content: reduce and add info on Markdown

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#447]
The homepage content is long and academic. Suggested to change to: 

> This tool helps you turn your accessibility evaluation findings into a report according to the Web Content Accessibility Guidelines Evaluation Methodology (WCAG-EM)
> 
> Tips for using this tool:
>  - As you use the tool, the Report page lists the success criteria that you have checked and not checked.
>  - You can export your report as HTML (web page) and as JSON (structured data).
>  - You can format your evaluation with Markdown, so that you can use lists, links and code examples. 

(Tips for using this tool copied from [ATAG Report Tool](https://atag-report-tool-hdv.vercel.app/), minus the tip about saving content as it was decided against that for this tool)

![image](https://user-images.githubusercontent.com/178782/119000672-99fcb400-b98b-11eb-87d4-72350909b26f.png)

**Comment by hidde** [comment]
@nitedog I have created a [demo showing an updated overview page](https://deploy-preview-467--wcag-em-report-tool-2021-redesign.netlify.app/). 

Main features:

1. Reduces content of first and second paragraph
2. Adds info on Markdown
3. Adds “Tips for using this tool above”
4. Adds section “About WCAG-EM and conformance reporting” (like ART has “About ATAG and authoring tools”) (do we want this?). This explanation was in the first paragraph before, I think it is helpful to give it its own background, and have an explicit heading that indicates this will provide background info
5. Adds section “Result choices”, like in ART (do we want this?)

Curious to hear what you think of this!

**Comment by hidde** [comment]
Removing from 28 May milestone as the issue needs discussion before closing.

**Comment by hidde** [comment]
Comment from @nitedog: remove Result Choices section.

@nitedog please let me know if there are other things you'd like to change and if you have input on a “About WCAG-EM and conformance reporting” section.

**Comment by nitedog** [comment]
I'm happy with the general approach of reducing the text at the start, and moving details into expand/collapse sections. I feel too much information was removed in this preview. For example, I think the information about saving is fairly important but seems lost.

I suggest:
1. Rename "About WCAG-EM and conformance reporting" to "About this tool"
2. Move much of what is currently in "What this tool does" into "About this tool"
3. Add back "Tips for using this tool" section (instead of "Result Choices" section)

**Comment by hidde** [comment]
> Rename "About WCAG-EM and conformance reporting" to "About this tool"

I feel that would make it less concrete and less to the point. It is also inconsistent with the ATAG Report Tool

> Move much of what is currently in "What this tool does" into "About this tool"

Is there anything in the “What this tool does” section that is not currently in the preview? I feel the content in the preview is much easier to parse.

> Add back "Tips for using this tool" section (instead of "Result Choices" section) 

Do we need all of those tips? I feel many of them are not needed given the content we display there now, others are very obvious (probably less obvious when the old tool launched many years ago, but much more obvious in 2021).

**Comment by nitedog** [comment]
> > Rename "About WCAG-EM and conformance reporting" to "About this tool"
> 
> I feel that would make it less concrete and less to the point. It is also inconsistent with the ATAG Report Tool

Difficult to say without content in this section. Will you really be explaining WCAG-EM and conformance reporting in this section?

> > Move much of what is currently in "What this tool does" into "About this tool"
> 
> Is there anything in the “What this tool does” section that is not currently in the preview? I feel the content in the preview is much easier to parse.

The information on saving; the fact this tool is not automated as many often expect; who the expected audience is (not for beginners); and maybe other points too.

> > Add back "Tips for using this tool" section (instead of "Result Choices" section)
> 
> Do we need all of those tips? I feel many of them are not needed given the content we display there now, others are very obvious (probably less obvious when the old tool launched many years ago, but much more obvious in 2021).

Not sure about your assumption, in particular for the last two points in that list. Not stuck on it either. But what is the problem if they are under expand/collapse and collapsed by default?

**Comment by hidde** [comment]
Discussed with @nitedog just now, Hidde to take first stab at it, we will then take it to EOWG for feedback.

**Comment by hidde** [comment]
Updated: 

* renamed "About WCAG-EM and conformance reporting" to "About this tool" (you were right, @nitedog )
* added that the tool it is not automated as “It does not perform (automated) checks.” explicitly under About this tool. It is also implicitly in the first sentence: “WCAG-EM Report Tool turns your accessibility evaluation findings into a report.”, it's _your_ findings, not some tool's findings
* added who the expected audience is to about this tool
* reviewed all tips and updated it for the redesign

**Comment by hidde** [comment]
Survey response from LK: 

> The overview page content seems just right to me.

**Comment by hidde** [comment]
discussed in EOWG on 25 June; generally people are happy with it, do want to have Start call to action as part of main content, which will be addressed in https://github.com/w3c/wcag-em-report-tool/issues/508
