### ISSUE TITLE
[Redesign] Clicking on categories in "Your report" block doesn't link correctly

### ISSUE THREAD

**Issue by mhansma96** [w3c/wcag-em-report-tool#454]
The site routes you to: /#@@@
Visible on step 4 in the "Your report" block on the right by clicking for example: Perceivable

**Comment by hidde** [comment]
Should link to the relevant heading in Audit Sample step.

For this, we'll have to: 

* add `id`'s to the princple headings 
* change the route to go to these hashes

Probably check how linking to SCs work and mimic that behavior

**Comment by hidde** [comment]
This was fixed in https://github.com/w3c/wcag-em-report-tool/pull/466
