### ISSUE TITLE
[Redesign] JSON-download misses some fields

### ISSUE THREAD

**Issue by mhansma96** [w3c/wcag-em-report-tool#461]
If you try to download the report as a JSON-file. If you've not visited the audit page, the criteria are not included. A solution to this, could be to initialize them beforehand, or to not show the downloadbutton if you haven't added any data in the audit page, which kinda makes sense. Also some overal data-fields like the report-author are missing the JSON, so those might not exist in the correct store, or not be updated correctly. 
A check to see which fields need to be there and to validate if they're there, is needed at the end of this.

**Comment by mhansma96** [comment]
I've found that there's only 2 fields missing: evaluator and commissioner. I am thinking there might be a reason for this, since you might import the criteria again in your report, but then you change these fields maybe anyway. Any thoughts on this?

**Comment by mhansma96** [comment]
Also I cannot export my assertions, just import them again to double check if all other fields are set after import. I keep getting one of the errors during the import. Not sure if that's because I am trying to import the same assertions, which would then make sense I guess. Is this behaviour normal?

**Comment by hidde** [comment]
maybe related https://github.com/w3c/wcag-em-report-tool/issues/470
