### ISSUE TITLE
[Redesign] relationship between "Report Findings" and "View Report" pages

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#475]
This may be somewhat related to #418 but maybe also a non-issue.

In the current version of WCAG-EM Report Tool, the content on the "View Report" page is not editable, it is a preview before downloading the report. Now it is editable, which reduces the need for the "Report Findings" page (except the "Record of evaluation specifics" field, all fields can be edited directly on the "View Report" page). Could these two pages be combined?

**Comment by hidde** [comment]
They could be, but not having Step 5 would mean being inconsistent with the steps in WCAG-EM?

I lean towards it's okay if users can edit this in two places; 

* in step 5, it is where they enter it
* in View Report, it is where they review it and have a chance to tweak if they see a problem

**Comment by nitedog** [comment]
We could also rename "View Report" to become Step 5? Is it worth getting broader perspectives on from EOWG or elsewhere before making such a big change?

**Comment by hidde** [comment]
Hm, but then it wouldn't reflect what Step 5 is in WCAG-EMa and be inconsistent with the ATAG Report Tool?

**Comment by nitedog** [comment]
Actually I think it would be very consistent with WCAG-EM. I'm not sure that this tool and the ATAG Report Tool need to have the exact same steps (and exact same sections in the intro).

**Comment by nitedog** [comment]
Retracting this issue after discussion with @hidde -- too much change at this stage.
