### ISSUE TITLE
[Redesign] Improve showing "Clear report" button

### ISSUE THREAD

**Issue by mhansma96** [w3c/wcag-em-report-tool#483]
The Clear Report button is now shown when you add a value to a criteria on the "Audit Sample" page. But what if we add other fields like the version, the title or target, shouldn't the button appear then as well?

**Comment by hidde** [comment]
I think we'd like this, but didn't do it previously because we didn't find a “clean” way to do it. If you do, feel free to make this work! (cc @nitedog)
