### ISSUE TITLE
Color of the input placeholder text doesn't take

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#49]
The color set for the placeholder text doesn't seem to apply to input elements, only the textareas work.

**Comment by rvantonisse** [comment]
Partially fixable with `::placeholder` css pseudo selector to style input placeholders. For Windows `-ms-high-contrast` can be used in some way. Se article: http://www.gwhitworth.com/blog/2017/04/how-to-use-ms-high-contrast/

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which we no longer use placeholders.
