### ISSUE TITLE
[bug; minor] Step 1 - weird spacing in info for "Website name"

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#495]
Empty line appears between 'Public Website of Example Organization' and 'Webshop of Example Company'.

**Comment by hidde** [comment]
No idea what causes that, the lines are separated with `br`s, for some reason the first one counts double, even if changing the order.

In 967e1f9, I have changed this into using an unordered lists, because yay semantics, this also solves the spacing problem.
