### ISSUE TITLE
More details for label "Show Info"

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag-em-report-tool#503]
Currently the label says "Show info". Should we specify the field which each of the "Show info" buttons relates to? Should that additional information be visible on screen or only available for screen readers?

**Comment by hidde** [comment]
Good point! In 015c321 I have added the relevant field names, so that “Show info” becomes “Show info for X”, where X is the name of the field or the text of the legend if it relates to a fieldset.
