### ISSUE TITLE
Label purpose for the buttons of the sample pages name

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag-em-report-tool#504]
1. Imported the report at https://github.com/w3c/wcag-em-report-tool/wiki/Example-report
1. Navigated to Step 3 "Select a representative sample"
1. Found a button called "contact" and pressed it.
1. Got a warning "Are you sure you want to delete this sample page?".

Is that the intention of such buttons? If so, I would put a clearer label, such as "Delete Contact"

**Comment by hidde** [comment]
Thanks for this, in a604bb2 I have just added a translated string “Delete” to these button names, so that it is like you propose, Delete, a space and then the name of the page you're deleting.
