### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mgifford** [w3c/wcag-em-report-tool#517]
What license is this released under?

Would love a LICENSE.md file to make that clear.

**Comment by hidde** [comment]
Have just added [LICENSE](https://github.com/w3c/wcag-em-report-tool/blob/master/LICENSE) file: this is licensed under the W3C License. 

Note this license also applies to the [redesigned tool](https://github.com/w3c/wai-wcag-em-report-tool/) and most other W3C tools and pages, let me know if you miss a `LICENSE` file in other places and I'll see what I can do.
