### ISSUE TITLE
The Sample to Evaluate section - Functionality Not Clear

### ISSUE THREAD

**Issue by TalyahAtUXAccess** [w3c/wcag-em-report-tool#520]
I must confess that I could not understand how to operate the Sample to Evaluate section with the "Set selected to complete" and "Set selected to Incomplete". I had to read the explanation several times but I still find it difficult to understand. If I knew exactly what it does, I would have been happy to offer a few alternative designs.
When evaluating applications, there are scenarios where different overlays are presented following users' actions. These overlays may include several different components that require a standalone audit and stand on their own. But they don't have a separate URL. In my report, I associate them to their main page but a report them on a separate chapter. The sample to evaluate does not provide the means of reporting on different interfaces on the same URL.

**Comment by hidde** [comment]
Thanks for this feedback! We have made a lot of updates to how this works in the [new tool](https://github.com/w3c/wai-wcag-em-report-tool/)  and look forward to hearing any feedback on these changes. There is no longer a “Set selected set to complete/incomplete”.

As for your use case: no, “sample to evaluate” does not help with that, you can add the URL once and report issues in different states of it in the report box for that URL.
