### ISSUE TITLE
https://www.w3.org/WAI/eval/report-tool/ doesn't seem to work

### ISSUE THREAD

**Issue by mgifford** [w3c/wcag-em-report-tool#529]
Maybe it's just me but https://www.w3.org/WAI/eval/report-tool/ isn't loading. At the very least it should redirect. 

Hmm. This is also broken:
https://w3.org/WAI/eval/report-tool

**Comment by daniel-montalvo** [comment]
Hi @mgifford 

There was an incident last week, and some services got affected.

https://status.w3.org/incidents/hrfr1phdc393

These two resources are working for me now. Is this the case for you?

Best.

**Comment by mgifford** [comment]
Works for me now. Thanks.
