### ISSUE TITLE
Optionally encapsulate bootstrap

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#62]
Provide a mechanism that allows including the app without bootstrap effecting the entire page.

**Comment by rvantonisse** [comment]
Implemented already partly by using bootstrap sass (include what is needed)? Need to replace the full bootstrap scss import with actual used bootstrap partials.
May also need to disable auto adding from bower components.

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which there is no more Bootstrap.
