### ISSUE TITLE
Step 4: add a "select all pages" to "sample to evaluate"

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#67]
to evaluate page-by-page you now have to first de-select all pages, then select the page that you want to have displayed. if you add a "select all pages" checkbox it could act like a toggle. when it is checked, all pages are or get checked. when it is directly unchecked from a checked state, all page get unchecked. when only some pages are checked or unchecked it remains unchecked.

**Comment by WilcoFiers** [comment]
Ready, it comes with a little toolbar for opening all selected pages and marking pages as (in)complete.
