### ISSUE TITLE
Feature to merge evaluations

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#75]
A feature that let's you combine evaluations would be very powerful. It could enable auditors to do audits of subsites and then combine those audits into a larger report. Some sort of conflict resolution would be required for this, as well as a way to potentially filter certain parts of an audit.

Another use case would be to compare the results of different audits. The purpose of this could be to detect reliability problems in tools or to measure the skill of a particular auditor. For this situation, being able to report the differences between multiple sources would be important.

**Comment by rvantonisse** [comment]
Partially implemented as "import" in toolbar / navbar.
- Any json-ld formatted with EARL Assertions will be able to be imported if they match with current sample, have a relation to any WCAG success criterion (id), have a result + outcome and an assertedBy property.
There is still room for improvement here, but should be added as enhancement issues.
Closing.
