### ISSUE TITLE
consider keeping progress bar on load and save pages

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#83]
consider keeping the start > step 1 > step 2 ... progress bar on the load/save pages so that people can jump back to their previous location more easily (eg. when they save data somewhere within the evaluation process, they can just go back to that page using the progress bar).

**Comment by nitedog** [comment]
This can be closed; [version 3](https://github.com/w3c/wai-wcag-em-report-tool) does not have these pages anymore.

**Comment by hidde** [comment]
We recently launched the [version 3 of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), so will close this issue, thanks @nitedog !
